var minicart = '<div class="popup">                                                                                                                                                                                                                                                                  ' +
    '           <div class="container mt-5 mb-5">                                                                                                                                                                                                                                                ' +
    '               <div class="d-flex justify-content-center row">                                                                                                                                                                                                                              ' +
    '                   <div class="col-md-12">                                                                                                                                                                                                                                                  ' +
    '                       <div class="p-2">                                                                                                                                                                                                                                                    ' +
    '                           <h4>Shopping cart</h4>                                                                                                                                                                                                                                           ' +
    '                       </div>                                                                                                                                                                                                                                                               ' +
    '                       <section id="cartList"></section>                                                                                                                                                                                                                                    ' +
    '                       <div class="d-flex flex-row align-items-center mt-3 p-2 bg-white rounded"><input type="text" class="form-control border-0 gift-card" placeholder="discount code/gift card"><button class="btn btn-outline-warning btn-sm ml-2" type="button">Apply</button></div>    ' +
    '                       <div class="d-flex flex-row align-items-center mt-3 p-2 bg-white rounded">                                                                                                                                                                                           ' +
    '                       </div>                                                                                                                                                                                                                                                               ' +
    '                   </div>                                                                                                                                                                                                                                                                   ' +
    '               </div>                                                                                                                                                                                                                                                                       ' +
    '           </div>                                                                                                                                                                                                                                                                           ' +
    '                                                                                                                                                                                                                                                                                            ' +
    '           <a class="close" href="#">&times;</a>                                                                                                                                                                                                                                            ' +
    '           <div class="container-fluid">                                                                                                                                                                                                                                                    ' +
    '               <div class="shopping-cart">                                                                                                                                                                                                                                                  ' +
    '                   <div class="totals">                                                                                                                                                                                                                                                     ' +
    '                       <div class="totals-item">                                                                                                                                                                                                                                            ' +
    '                           <label>Subtotal</label>                                                                                                                                                                                                                                          ' +
    '                           <div class="totals-value" id="cart-subtotal"></div>                                                                                                                                                                                                              ' +
    '                       </div>                                                                                                                                                                                                                                                               ' +
    '                       <div class="totals-item">                                                                                                                                                                                                                                            ' +
    '                           <label>Tax (0%)</label>                                                                                                                                                                                                                                          ' +
    '                           <div class="totals-value" id="cart-tax"></div>                                                                                                                                                                                                                   ' +
    '                       </div>                                                                                                                                                                                                                                                               ' +
    '                       <div class="totals-item">                                                                                                                                                                                                                                            ' +
    '                           <label>Shipping</label>                                                                                                                                                                                                                                          ' +
    '                           <div class="totals-value" id="cart-shipping">15.00</div>                                                                                                                                                                                                         ' +
    '                       </div>                                                                                                                                                                                                                                                               ' +
    '                       <div class="totals-item totals-item-total">                                                                                                                                                                                                                          ' +
    '                           <label>Grand Total</label>                                                                                                                                                                                                                                       ' +
    '                           <div class="totals-value" id="cart-total"></div>                                                                                                                                                                                                                 ' +
    '                       </div>                                                                                                                                                                                                                                                               ' +
    '                   </div>                                                                                                                                                                                                                                                                   ' +
    '                   <button class="checkout">Checkout</button>                                                                                                                                                                                                                               ' +
    '               </div>                                                                                                                                                                                                                                                                       ' +
    '           </div>                                                                                                                                                                                                                                                                           ' +
    '       </div>                                                                                                                                                                                                                                                                               ';
document.getElementById('miniCart').innerHTML = minicart;